### ISSUE TITLE
Include eztv as official qbittorrent plugin

### ISSUE THREAD

**Issue by ngosang** [nindogo/qbtSearchScripts#1]
@nindogo 
Hi, I'm the official maintainer of qbittorrent plugins.
I want to promote this plugin to official. If you are interested:

1. Open a PR here https://github.com/qbittorrent/search-plugins
2. ~~Fix the "leechers" value~~
3. Test the plugin with python2 and python3
4. Copy the same code to folders `nova` and `nova3`
5. Add it to files `nova/versions.txt` and `nova3/versions.txt`

I will review and merge the code asap.
Thank you

**Comment by nindogo** [comment]
Hi all,

thanks for the message and considering the addition of eztv as an official search engine.

Thing is the search page does not have leechers values. I can get them in the pages but it will be slow as we will need to open all desc_links.
I was lazy - so I just focussed on python3. It will take some time to get it on python2.

Ni

**Comment by ngosang** [comment]
I din't see the home page, we don't need the leechers then :smile: 
I can port it to python2 if you leet me.

**Comment by nindogo** [comment]
You are welcome to do so if you want.

eztv.ag places all the results in one page so it is an easy one to work with.

Ni

**Comment by ngosang** [comment]
Implemented here https://github.com/qbittorrent/search-plugins/pull/41
