### ISSUE TITLE
TorrentGalaxy.to no longer working

### ISSUE THREAD

**Issue by troysjanda** [nindogo/qbtSearchScripts#14]
The search pluing is no longer working

**Comment by nindogo** [comment]
Working now  - but only for page one  because of captcha and how it works. Also maybe it won't work because of reasons .... lol.

Try now @troysjanda .

**Comment by troysjanda** [comment]
I can check when I get home tonight after work.

**Comment by nindogo** [comment]
> I can check when I get home tonight after work.

Did it work?

**Comment by troysjanda** [comment]
Have not been able too check, my daughter is in the hospital and most
likely will be home tomorrow or Tuesday. I'm sorry.

**Comment by nindogo** [comment]
> Have not been able too check, my daughter is in the hospital and most likely will be home tomorrow or Tuesday. I'm sorry.
> […](#)

Oh dude sorry. Hope she get's better. Please focus on that.

**Comment by nindogo** [comment]
Hey @faelana could you please check?

**Comment by troysjanda** [comment]
Just checked and seems to be working, I did a search for Titanic and got
results. I can further test it tonight when I get home from work. Thank you.

**Comment by nindogo** [comment]
> I can further test it tonight when I get home from work.

Thanks I will close it. It does not always go beyond page one but that is an issue with the website. I will close.

BTW how is your kid?

**Comment by faelana** [comment]
> Hey @faelana could you please check?

@nindogo  Yes, just tried 0.7 it and it works now. Sorry for the late reply, thank you!
